### ISSUE TITLE
[not a bug] How can I update this to the latest Keystone

### ISSUE THREAD

**Issue by faddat** [dvdcastro/keystonejs-ng-skeleton#3]
Just curious what your procedure is, before I go and break the thing and submit a broken/improper PR, etc....

**Comment by dvdcastro** [comment]
Just change the version number in the `package.json` file, do a `npm install` and check if anything is broken.

**Comment by faddat** [comment]
@dvdcastro thanks!  I know more or less nothing of Node :).
