### ISSUE TITLE
angular in .gitignore

### ISSUE THREAD

**Issue by kriskater** [dvdcastro/keystonejs-ng-skeleton#5]
I have cloned your project to study both angular and keystonejs, but it is missing the angular javascript files. Did you put it in your .gitignore on purpose or by accident? What version of angular should be used with your project?

**Comment by dvdcastro** [comment]
Hello,

Sorry for the late response. The project uses [bower](http://bower.io/) for installing its dependencies. You should install bower first:

    npm install -g bower

And then, on the project's folder:

    npm install

The npm install executes bower at the end, which will install angular for you.
